<?php
/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum
 * of the even-valued terms.
 */

function fibonacciFilter( $n ) {
	$sum    = 0;
	$first  = 0;
	$second = 1;
	$third  = 2;
	for ( $i = 0; $third < $n; $first = $second, $second = $third, $i ++ ) {
		$third = $first + $second;
		if ( $third % 2 === 0 ) {
			$sum += $third;
		}
	}

	return $sum;
}

echo fibonacciFilter( 4000000 );